import test from 'node:test';import assert from 'node:assert/strict';import {baseBatch,verifyCandidates,saveVerified,syncBaseAddressHistory} from '../server/base-backfill.mjs';import {createDb} from '../scripts/local-db.mjs';
const h='0x'+'a'.repeat(64),b='0x'+'b'.repeat(64),sender='0x589a2314a2e05f45e40c4823da3ba58d421db3d8',asset='0x833589fcd6edb6e08f4c7c32d4f71b54bda02913';
const tx={hash:h,from:sender,to:asset,input:'0xe3ee160e',blockHash:b,blockNumber:'0x10'},block={hash:b,number:'0x10',timestamp:'0x65000000'},receipt={transactionHash:h,blockHash:b,blockNumber:'0x10',status:'0x1',logs:[{address:asset,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+'1'.repeat(64),'0x'+'2'.repeat(64)],data:'0x'+'0'.repeat(60)+'1000',transactionHash:h,blockHash:b,logIndex:'0x1'}]};
function mock(options={}){return async(_url,o)=>{const req=JSON.parse(o.body);return Response.json(req.map(q=>({id:q.id,result:q.method==='eth_chainId'?'0x2105':q.method==='eth_getTransactionByHash'?{...tx,...options.tx}:q.method==='eth_getTransactionReceipt'?{...receipt,...options.receipt}:block})).reverse())}}
test('batch matches out of order ids and rejects duplicate responses',async()=>{const old=global.fetch;try{global.fetch=mock();assert.equal((await baseBatch({},[['eth_chainId',[]]]))[0],'0x2105');global.fetch=async()=>Response.json([{id:0,result:1},{id:0,result:2}]);await assert.rejects(baseBatch({},[['a',[]],['b',[]]]),/Invalid RPC/)}finally{global.fetch=old}});
test('candidate receipts use canonical block identity and exclude ordinary transfers',async()=>{const old=global.fetch;try{global.fetch=mock();const records=await verifyCandidates({},[h,h]);assert.equal(records.length,1);assert.equal(records[0].facilitator,'xpay');const db=createDb();await saveVerified(db,records);await saveVerified(db,records);assert.equal(db.raw.prepare('SELECT count(*) n FROM receipts').get().n,1);global.fetch=mock({tx:{input:'0xa9059cbb'}});assert.equal((await verifyCandidates({},[h])).length,0);global.fetch=mock({receipt:{blockHash:'0x'+'c'.repeat(64)}});await assert.rejects(verifyCandidates({},[h]),/identity mismatch/)}finally{global.fetch=old}});
test('failed RPC keeps candidate queue for retry instead of skipping page',async()=>{const old=global.fetch,DB=createDb();try{global.fetch=async(url,o)=>o?.method==='POST'?Response.json({error:'throttled'},{status:429}):Response.json({items:[{hash:h,token:{address_hash:asset},transaction_hash:h}],next_page_params:{block_number:10}});const r=await syncBaseAddressHistory({DB});assert.match(r.error,/429/);const row=DB.raw.prepare('SELECT * FROM address_backfills WHERE id=?').get(r.job);assert.equal(row.complete,0);assert.deepEqual(JSON.parse(row.queue),[h]);}finally{global.fetch=old}});
test('batched range collection validates receipts and advances the final block only',async()=>{const {collectBaseRange}=await import('../server/base.mjs');const old=global.fetch;try{global.fetch=async(_url,o)=>Response.json(JSON.parse(o.body).map(q=>({id:q.id,result:q.method==='eth_getTransactionReceipt'?receipt:{...block,transactions:[tx]}})).reverse());const r=await collectBaseRange({BASE_USE_BATCH_RPC:'true'},16,16);assert.equal(r.records.length,1);assert.equal(r.checkpoint.number,'0x10')}finally{global.fetch=old}});
test('catalog merchants are queued and completed addresses become eligible again',async()=>{const old=global.fetch,DB=createDb(),merchant='0x'+'3'.repeat(40);try{global.fetch=async(url,o)=>o?.method==='POST'?mock()(url,o):Response.json({items:[],next_page_params:null});await syncBaseAddressHistory({DB,BASE_MERCHANT_ADDRESSES:[merchant,merchant,'invalid']});assert.equal(DB.raw.prepare('SELECT count(*) n FROM address_backfills WHERE id=?').get('merchant-'+merchant).n,1);DB.raw.prepare('UPDATE address_backfills SET complete=1,checked_at=0 WHERE id=?').run('merchant-'+merchant);await syncBaseAddressHistory({DB,BASE_MERCHANT_ADDRESSES:[merchant]});const row=DB.raw.prepare('SELECT * FROM address_backfills WHERE id=?').get('merchant-'+merchant);assert.ok(row.complete===0||row.checked_at>0);}finally{global.fetch=old}});
test('history persists the first group when the next group fails',async()=>{const old=global.fetch,DB=createDb(),hashes=Array.from({length:10},(_,i)=>'0x'+(i+1).toString(16).padStart(64,'0'));let groups=0;try{global.fetch=async(url,o)=>{if(o?.method!=='POST')return Response.json({items:hashes.map(hash=>({hash,transaction_hash:hash,token:{address_hash:asset}})),next_page_params:{block_number:10}});const req=JSON.parse(o.body);if(req.some(q=>q.method==='eth_getTransactionByHash')&&++groups===2)return Response.json({}, {status:429});return Response.json(req.map(q=>({id:q.id,result:q.method==='eth_chainId'?'0x2105':q.method==='eth_getTransactionByHash'?{...tx,hash:q.params[0]}:q.method==='eth_getTransactionReceipt'?{...receipt,transactionHash:q.params[0],logs:receipt.logs.map(l=>({...l,transactionHash:q.params[0]}))}:block})));};const r=await syncBaseAddressHistory({DB});assert.match(r.error,/429/);const row=DB.raw.prepare('SELECT * FROM address_backfills WHERE id=?').get(r.job);assert.deepEqual(JSON.parse(row.queue),hashes.slice(5));assert.equal(row.verified,5);assert.equal(DB.raw.prepare('SELECT count(*) n FROM receipts').get().n,5);}finally{global.fetch=old}});
