import {syncSolana,syncXrp,nativeStatus} from './native-indexers.mjs';
import {openApi} from './openapi.mjs';
import {analytics,sellerDirectory} from './analytics.mjs';
import {syncBase,baseStatus} from './base.mjs';
import {listParticipants,addressActivity,validateAddress} from './participants.mjs';
import {lookupTransaction,validateLookup,LookupError} from './lookup.mjs';
import {SNAPSHOT} from './catalog-snapshot.mjs';
import {syncBsc,bscStatus} from './bsc.mjs';
import {BSC_TOPIC} from './event-topic.mjs';
import {SOURCES,NETWORKS,networkName,safeUrl,normalizeResources,dedupeResources} from './sources.mjs';
export async function syncAll(env){return Promise.allSettled([syncSources(env),syncBsc(env,BSC_TOPIC),syncBase(env),syncSolana(env),syncXrp(env)])}
const TTL=15*60*1000,MAX_BODY=100000,MAX_UPSTREAM=2_000_000;
export class ApiError extends Error{constructor(status,message){super(message);this.status=status}}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const clean=(s,n=200)=>typeof s==='string'?s.trim().slice(0,n):'';
function identity(req){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');return id&&email?{id,email}:null}
function isAdmin(req,env){const user=identity(req);return !!(user&&String(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(x=>x.trim()).includes(user.email.toLowerCase()))}
function requireUser(req){const user=identity(req);if(!user)throw new ApiError(401,'Sign in with ChatGPT to continue.');return user}
function requireAdmin(req,env){if(!isAdmin(req,env))throw new ApiError(403,'Administrator access required.')}
function csrf(req){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new ApiError(403,'Same-origin request required.')}
export async function limitedJson(req,limit=MAX_BODY){if(Number(req.headers.get('content-length'))>limit)throw new ApiError(413,'Request too large.');const reader=req.body?.getReader();if(!reader)throw new ApiError(400,'JSON body required.');let total=0,parts=[];for(;;){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new ApiError(413,'Request too large.')}parts.push(value)}const bytes=new Uint8Array(total);let at=0;for(const p of parts){bytes.set(p,at);at+=p.length}try{return JSON.parse(new TextDecoder().decode(bytes))}catch{throw new ApiError(400,'Invalid JSON.')}}
async function upstream(url){const res=await fetch(url,{headers:{accept:'application/json','user-agent':'x402Blockchains-Discovery/1.0'},redirect:'manual',signal:AbortSignal.timeout(5000)});if(!res.ok)throw new Error('HTTP '+res.status);const data=await limitedJson(res,MAX_UPSTREAM);return data}
async function rate(db,key,max,windowMs){const now=Date.now();const r=await db.prepare('INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<? THEN excluded.expires_at ELSE expires_at END RETURNING count').bind(key,now+windowMs,now,now).first();if(r.count>max)throw new ApiError(429,'Too many requests. Try again later.')}
async function sourceRows(db){return(await db.prepare('SELECT * FROM source_cache').all()).results||[]}
async function fetchSource(source,previous,{pages=5}={}){
 const data={networks:[],kinds:[],resources:[],catalog:previous?.catalog||null,stats:null};let success=false;
 try{const response=await upstream(source.url+source.supported);if(!Array.isArray(response.kinds))throw new Error('Unsupported discovery schema');data.kinds=response.kinds.filter(k=>networkName(k.network)).map(k=>({network:networkName(k.network),networkId:k.network,scheme:k.scheme,version:k.x402Version}));data.networks=[...new Set(data.kinds.map(k=>k.network))];success=true}catch(e){data.error=String(e.message).slice(0,150)}
 if(source.discovery){let offset=previous?.catalog?.complete?0:(previous?.catalog?.offset||0);const sweep=offset?(previous?.catalog?.sweep||Date.now()):Date.now();let total=null,complete=false;const started=Date.now();try{
 for(let page=0;page<pages;page++){const response=await upstream(source.url+source.discovery+'?limit=100&offset='+offset);if(!Array.isArray(response.items))throw new Error('Unsupported catalog schema');total=Number.isSafeInteger(response.pagination?.total)?response.pagination.total:null;const signature=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(response.items.map(r=>[r.resource||r.url,r.method])))))).map(n=>n.toString(16).padStart(2,'0')).join('');if(response.items.length&&signature===data.catalog?.lastPage)throw new Error('Provider repeated a catalog page');data.resources.push(...normalizeResources(response,source.id));offset+=response.items.length;complete=total!==null?offset>=total:response.items.length<100;if(!response.items.length&&!complete)throw new Error('Provider ended before reported total');data.catalog={total,offset,complete,sweep,lastPage:signature,updatedAt:Date.now(),lastCompleteAt:complete?Date.now():(previous?.catalog?.lastCompleteAt||null),error:null};if(complete||Date.now()-started>12000)break;}
 }catch(e){data.catalog={...(data.catalog||{}),error:String(e.message).slice(0,150)};}}
 if(source.stats&&success)try{data.stats=await upstream(source.url+source.stats)}catch(e){data.statsError=String(e.message).slice(0,150)}return{data,success};
}
export async function syncSources(env,{force=false,pages=5,maxSources=3}={}){
 if(!env.DB)throw new ApiError(503,'Database unavailable.');const now=Date.now();const lock=await env.DB.prepare('INSERT INTO sync_locks(id,until) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET until=excluded.until WHERE sync_locks.until<? RETURNING id').bind('sources',now+90000,now).first();if(!lock)return{busy:true};
 try{const saved=await sourceRows(env.DB);const due=SOURCES.filter(s=>s.supported).filter(s=>{const old=saved.find(r=>r.id===s.id);let prior;try{prior=JSON.parse(old?.payload||'{}')}catch{}return force||!old||now-old.checked_at>(s.discovery&&prior?.catalog&&!prior.catalog.complete&&!prior.catalog.error?10000:TTL)}).sort((a,b)=>(saved.find(r=>r.id===a.id)?.checked_at||0)-(saved.find(r=>r.id===b.id)?.checked_at||0)).slice(0,maxSources);
 await Promise.all(due.map(async source=>{const old=saved.find(r=>r.id===source.id);let prior;try{prior=JSON.parse(old?.payload||'null')}catch{}const {data,success}=await fetchSource(source,prior,{pages});
 if(source.discovery&&data.catalog?.sweep){const writes=data.resources.map(r=>env.DB.prepare('INSERT INTO service_cache(source,url,method,payload,seen_sweep) VALUES (?,?,?,?,?) ON CONFLICT(source,url,method) DO UPDATE SET payload=excluded.payload,seen_sweep=excluded.seen_sweep').bind(source.id,r.url,r.method,JSON.stringify(r),data.catalog.sweep));for(let at=0;at<writes.length;at+=50)await env.DB.batch(writes.slice(at,at+50));if(data.catalog.complete&&!data.catalog.error)await env.DB.prepare('DELETE FROM service_cache WHERE source=? AND seen_sweep<>?').bind(source.id,data.catalog.sweep).run();data.catalog.fetched=(await env.DB.prepare('SELECT COUNT(*) n FROM service_cache WHERE source=?').bind(source.id).first()).n;}
 delete data.resources;const payload={...(prior||{}),...data,...(!success?{networks:prior?.networks||[],kinds:prior?.kinds||[]}:{} )};await env.DB.prepare('INSERT INTO source_cache(id,payload,checked_at,success_at,error) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,checked_at=excluded.checked_at,success_at=excluded.success_at,error=excluded.error').bind(source.id,JSON.stringify(payload),now,success?now:(old?.success_at||null),success?null:data.error).run();}));await env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(now).run();return{checked:due.length};
 }finally{await env.DB.prepare('DELETE FROM sync_locks WHERE id=?').bind('sources').run()}
}
function publicSource(s,row){const snapshot=SNAPSHOT.sources.find(r=>r.id===s.id);let payload={};try{payload=JSON.parse(row?.payload||'{}')}catch{}const useSnapshot=snapshot&&(!row||snapshot.checkedAt>row.checked_at);if(useSnapshot){payload=snapshot;row={checked_at:snapshot.checkedAt,success_at:snapshot.successAt,error:snapshot.error};}return{...s,supported:undefined,discovery:undefined,stats:undefined,state:s.deprecated?'deprecated':!s.supported?'not_connected':!row?'not_checked':row.error?'unavailable':Date.now()-row.checked_at>TTL?'stale':'connected',networks:payload.networks||[],kinds:payload.kinds||[],catalog:s.discovery?(payload.catalog||null):null,checkedAt:row?.checked_at||null,successAt:row?.success_at||null,error:row?.error||null,stats:payload.stats||null,statsError:payload.statsError||null,snapshotAt:snapshot?.checkedAt||null,scope:'Provider-reported capabilities and catalog metadata; not verified payment history.'};}
function filterParams(url){const network=url.searchParams.get('network')||'All';if(network!=='All'&&!NETWORKS.some(n=>n.id===network))throw new ApiError(400,'Invalid network.');const days=Number(url.searchParams.get('days')||1);if(![0,1,7,30].includes(days))throw new ApiError(400,'Invalid time range.');const page=Number(url.searchParams.get('page')||1),limit=Number(url.searchParams.get('limit')||20);if(!Number.isInteger(page)||page<1||page>10000||!Number.isInteger(limit)||limit<1||limit>100)throw new ApiError(400,'Invalid pagination.');return{network,days,page,limit,q:clean(url.searchParams.get('q'),150).toLowerCase()}}
export async function discovery(db){const rows=await sourceRows(db);const cached=(await db.prepare('SELECT payload FROM service_cache').all()).results;const live=cached.flatMap(r=>{try{return[JSON.parse(r.payload)]}catch{return[]}});const completed=new Set(rows.filter(r=>{try{const c=JSON.parse(r.payload).catalog;return (c?.lastCompleteAt||(c?.complete&&!c.error?c.updatedAt:0))>SNAPSHOT.generatedAt}catch{return false}}).map(r=>r.id));const snapshot=SNAPSHOT.resources.filter(r=>!completed.has(r.source));const bySource=new Map(snapshot.map(r=>[r.source+' '+r.method+' '+r.url,r]));for(const r of live)bySource.set(r.source+' '+r.method+' '+r.url,r);return{sources:SOURCES.map(s=>publicSource(s,rows.find(r=>r.id===s.id))),resources:dedupeResources([...bySource.values()]),snapshotAt:SNAPSHOT.generatedAt};}
export function groupOrigins(resources){const map=new Map();for(const r of resources){const origin=new URL(r.url).origin;let p=map.get(origin);if(!p){p={id:encodeURIComponent(origin),name:r.name,website:origin,description:r.description,networks:[],sources:[],services:[],evidence:'provider-catalog',status:'discovered'};map.set(origin,p)}for(const a of r.accepts)if(!p.networks.includes(a.network))p.networks.push(a.network);for(const source of r.sources)if(!p.sources.includes(source))p.sources.push(source);p.services.push(r);}return [...map.values()].sort((a,b)=>b.services.length-a.services.length||a.name.localeCompare(b.name));}
export function validateProject(data){const name=clean(data.name,100),description=clean(data.description,2500),category=clean(data.category,60),contact=clean(data.contact,200),paymentTerms=clean(data.paymentTerms,2000),website=safeUrl(data.website),endpoint=safeUrl(data.endpoint),docs=safeUrl(data.docs);const networks=Array.isArray(data.networks)?[...new Set(data.networks)]:[];if(name.length<2||description.length<30||!category||!website||!endpoint||!docs||!contact||!paymentTerms||!networks.length||networks.some(n=>!NETWORKS.some(x=>x.id===n)))throw new ApiError(400,'Provide a name, description (30+ characters), category, valid HTTPS website, endpoint, documentation, contact, payment terms and supported networks.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact))throw new ApiError(400,'Enter a valid contact email.');return{name,description,category,contact,paymentTerms,website,endpoint,docs,networks}}
function publicProject(row,owner=false){if(!row)return null;return{id:row.id,name:row.name,website:row.website,description:row.description,category:row.category,networks:JSON.parse(row.networks),endpoint:row.endpoint,docs:row.docs,paymentTerms:row.payment_terms,status:row.status,reviewNote:row.review_note,createdAt:row.created_at,updatedAt:row.updated_at,...(owner?{contact:row.contact}:{})}}
export function validateReceipt(r,source){const network=networkName(r.network)||NETWORKS.find(n=>n.id===r.network)?.id;const transaction=clean(r.transaction,140),eventId=clean(r.eventId,80)||'0';const isEvm=['Base','BSC'].includes(network);if(!network||!(isEvm?/^0x[0-9a-fA-F]{64}$/.test(transaction):network==='XRP'?/^[0-9a-fA-F]{64}$/.test(transaction):/^[1-9A-HJ-NP-Za-km-z]{80,90}$/.test(transaction)))throw new ApiError(400,'Invalid network or transaction hash.');if(!/^[0-9]{1,60}$/.test(r.amount)||!Number.isInteger(r.decimals)||r.decimals<0||r.decimals>36||!clean(r.asset,150)||!Number.isSafeInteger(r.timestamp)||r.timestamp<1500000000000||r.timestamp>Date.now()+60000||!['settled','pending','failed'].includes(r.status))throw new ApiError(400,'Invalid receipt fields.');if(!/^[a-zA-Z0-9:_-]{1,80}$/.test(eventId))throw new ApiError(400,'Invalid event identifier.');return{network,transaction:isEvm||network==='XRP'?transaction.toLowerCase():transaction,eventId,source,payer:clean(r.payer,150)||null,payTo:clean(r.payTo,150)||null,resource:r.resource?safeUrl(r.resource):null,asset:clean(r.asset,150),amount:r.amount,decimals:r.decimals,timestamp:r.timestamp,status:r.status}}
async function verifyWebhook(req,env,source,body){let keys={};try{keys=JSON.parse(env.INGEST_KEYS_JSON||'{}')}catch{}const secret=keys[source];if(!secret)throw new ApiError(403,'This source has no ingestion key configured.');const stamp=req.headers.get('x-timestamp')||'',signature=req.headers.get('x-signature')||'';if(!/^\d{13}$/.test(stamp)||Math.abs(Date.now()-Number(stamp))>300000||!/^sha256=[a-f0-9]{64}$/.test(signature))throw new ApiError(401,'Invalid webhook signature or timestamp.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const bytes=Uint8Array.from(signature.slice(7).match(/../g).map(x=>parseInt(x,16)));if(!await crypto.subtle.verify('HMAC',key,bytes,new TextEncoder().encode(stamp+'.'+body)))throw new ApiError(401,'Invalid webhook signature.')}
async function api(req,env,ctx){const url=new URL(req.url),path=url.pathname.replace(/^\/api\/v1(?=\/)/,'/api'),db=env.DB;if(req.method==='GET'&&env.COLLECTOR_API_URL&&['/api/overview','/api/analytics','/api/transactions','/api/participants','/api/address','/api/transaction','/api/indexers','/api/bsc/status'].includes(path)){const upstream=new URL(env.COLLECTOR_API_URL);if(upstream.protocol!=='https:'||upstream.origin===url.origin)throw new ApiError(503,'Collector URL is not configured correctly.');upstream.pathname=upstream.pathname.replace(/\/$/,'')+path;upstream.search=url.search;const response=await fetch(upstream,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new ApiError(503,'The continuous collector is unavailable. Please retry.');const result=await limitedJson(response,4_000_000);return json(result);}if(path==='/api/openapi.json')return json(openApi);if(path==='/api/health')return json({ok:!!db,storage:db?'configured':'unavailable',version:1});if(path==='/api/session')return json({user:identity(req)?{signedIn:true}:null,admin:isAdmin(req,env)});if(!db)throw new ApiError(503,'Database unavailable. Please try again later.');if(req.method==='GET'){
if(['/api/sources','/api/services','/api/overview','/api/facilitators','/api/ecosystem'].includes(path)||path.startsWith('/api/origins/'))ctx.waitUntil(syncSources(env).catch(()=>{}));
if(path==='/api/participants'){const p=filterParams(url),role=url.searchParams.get('role');if(!['buyers','sellers'].includes(role))throw new ApiError(400,'Choose buyers or sellers.');return json(await listParticipants(db,{...p,role}));}
if(path==='/api/address'){const p=filterParams(url),address=url.searchParams.get('address');if(!validateAddress(p.network,address))throw new ApiError(400,'Enter a valid address for the selected chain.');return json(await addressActivity(db,{...p,address}));}
if(path==='/api/transaction'){const network=url.searchParams.get('network'),hash=validateLookup(network,url.searchParams.get('hash'));await rate(db,'lookup:'+(identity(req)?.id||req.headers.get('cf-connecting-ip')||'anonymous'),30,60000);const indexed=(await db.prepare('SELECT * FROM receipts WHERE network=? AND `transaction`=? ORDER BY event_id').bind(network,hash).all()).results;try{const result=await lookupTransaction(env,network,hash);return json({...result,indexedReceipts:indexed,coverage:indexed.length?'This transaction has indexed receipt evidence; inspect each receipt source.':'No x402 receipt is indexed for this transaction. A blockchain confirmation alone does not establish an x402 purchase.'})}catch(e){if(e instanceof LookupError&&indexed.length)return json({network,hash,status:'indexed',indexedReceipts:indexed,lookupError:e.message,explorer:NETWORKS.find(n=>n.id===network).explorer+hash,coverage:'Receipt records are available; direct chain lookup is currently unavailable.'});throw e}}
if(path==='/api/bsc/status'){ctx.waitUntil(syncBsc(env,BSC_TOPIC).catch(()=>{}));return json(await bscStatus(env));}
if(path==='/api/sources'){const d=await discovery(db);return json({base:await baseStatus(env),bsc:await bscStatus(env),items:d.sources,coverage:'Curated, expanding source registry. Not exhaustive; public availability varies.',updatedAt:Date.now()})}
if(path==='/api/facilitators'){const p=filterParams(url),d=await discovery(db);const list=d.sources.filter(s=>s.role==='facilitator');const all=list.filter(s=>(p.network==='All'||s.networks.includes(p.network)||s.declared.includes(p.network))&&[s.name,s.url,...s.declared].join(' ').toLowerCase().includes(p.q)).map(s=>({...s,services:d.resources.filter(r=>r.sources.includes(s.id)).length}));return json({items:all.slice((p.page-1)*p.limit,p.page*p.limit),total:all.length,page:p.page,registered:list.length,responding:list.filter(s=>s.state==='connected').length,snapshotAt:d.snapshotAt});}
if(path==='/api/ecosystem'){const p=filterParams(url),d=await discovery(db);const all=groupOrigins(d.resources).filter(r=>(p.network==='All'||r.networks.includes(p.network))&&[r.name,r.website,r.description].join(' ').toLowerCase().includes(p.q));return json({items:all.slice((p.page-1)*p.limit,p.page*p.limit).map(({services,...p})=>({...p,serviceCount:services.length})),total:all.length,page:p.page,snapshotAt:d.snapshotAt});}
if(path.startsWith('/api/origins/')){const origin=decodeURIComponent(path.slice(13)),d=await discovery(db),p=groupOrigins(d.resources).find(p=>p.website===origin);if(!p)throw new ApiError(404,'Project origin not found.');const filters=filterParams(url);return json({...p,services:p.services.slice((filters.page-1)*filters.limit,filters.page*filters.limit),total:p.services.length,page:filters.page,limit:filters.limit,snapshotAt:d.snapshotAt});}
if(path==='/api/services'){const p=filterParams(url),d=await discovery(db);const source=url.searchParams.get('source');const all=d.resources.filter(r=>(!source||r.sources.includes(source))&&(p.network==='All'||r.accepts.some(a=>a.network===p.network))&&[r.name,r.url,r.description].join(' ').toLowerCase().includes(p.q));return json({items:all.slice((p.page-1)*p.limit,p.page*p.limit),total:all.length,page:p.page,limit:p.limit,partial:d.sources.some(s=>s.catalog&&!s.catalog.complete),sources:d.sources.filter(s=>s.catalog).map(s=>({id:s.id,state:s.state,checkedAt:s.checkedAt,catalog:s.catalog}))})}
if(path==='/api/indexers')return json({base:await baseStatus(env),baseHistory:await baseStatus({...env,BASE_CURSOR_ID:'base-history-v1'}),bsc:await bscStatus(env),bscHistory:await bscStatus({...env,BSC_CURSOR_ID:'bsc-history-v1'}),native:await nativeStatus(env),continuous:env.SELF_HOSTED_COLLECTOR==='true',operation:env.SELF_HOSTED_COLLECTOR==='true'?'Independent collector deployment. Check checkpoint timestamps and errors to verify scheduled ingestion progress.':'Hosted batches run on visits or administrator requests. Self-host the collector for continuous ingestion.'});
if(path==='/api/analytics'){const p=filterParams(url),d=await discovery(db);return json(await analytics(db,{...p,origin:url.searchParams.get('origin'),facilitator:url.searchParams.get('facilitator')},d.resources,SOURCES))}
if(path==='/api/overview'){ctx.waitUntil(syncSolana(env).catch(()=>{}));ctx.waitUntil(syncXrp(env).catch(()=>{}));ctx.waitUntil(syncBase(env).catch(()=>{}));ctx.waitUntil(syncBsc(env,BSC_TOPIC).catch(()=>{}));const p=filterParams(url),d=await discovery(db);const since=p.days?Date.now()-p.days*86400000:0;const where=p.network==='All'?'timestamp>=?':'timestamp>=? AND network=?';const binds=p.network==='All'?[since]:[since,p.network];const aggregate=await db.prepare(`SELECT COUNT(*) AS count, COUNT(DISTINCT CASE WHEN status='settled' AND payer IS NOT NULL AND payer<>'' THEN network||':'||CASE WHEN network IN ('Base','BSC') THEN lower(payer) ELSE payer END END) AS buyers, COUNT(DISTINCT CASE WHEN status='settled' AND pay_to IS NOT NULL AND pay_to<>'' THEN network||':'||CASE WHEN network IN ('Base','BSC') THEN lower(pay_to) ELSE pay_to END END) AS sellers FROM receipts WHERE `+where).bind(...binds).first();const hours=(await db.prepare('SELECT CAST(timestamp/3600000 AS INTEGER)*3600000 AS time, COUNT(*) AS count FROM receipts WHERE '+where+' GROUP BY time ORDER BY time').bind(...binds).all()).results;return json({network:p.network,days:p.days,indexedTransactions:aggregate.count,buyers:aggregate.buyers,sellers:aggregate.sellers,volumeUsd:null,projects:groupOrigins(d.resources.filter(r=>p.network==='All'||r.accepts.some(a=>a.network===p.network))).length,registeredFacilitators:d.sources.filter(s=>s.role==='facilitator'&&(p.network==='All'||s.declared.includes(p.network)||s.networks.includes(p.network))).length,snapshotAt:d.snapshotAt,history:hours,networks:NETWORKS.map(n=>({ ...n,services:d.resources.filter(r=>r.accepts.some(a=>a.network===n.id)).length,facilitators:d.sources.filter(s=>s.networks.includes(n.id)&&s.state==='connected').length})),sources:d.sources.filter(s=>s.state==='connected'&&(p.network==='All'||s.networks.includes(p.network))).length,services:d.resources.filter(r=>p.network==='All'||r.accepts.some(a=>a.network===p.network)).length,coverage:'Transactions cover configured receipt feeds, scoped BSC router events and inferred Base facilitator authorization transfers. Discovery does not provide complete payment history. USD volume is unavailable without verified valuation.',checkedAt:Math.max(0,...d.sources.map(s=>s.checkedAt||0))})}
if(path==='/api/transactions'){const p=filterParams(url),status=url.searchParams.get('status')||'all';if(!['all','settled','pending','failed'].includes(status))throw new ApiError(400,'Invalid status.');const clauses=['timestamp>=?'],binds=[p.days?Date.now()-p.days*86400000:0];if(p.network!=='All'){clauses.push('network=?');binds.push(p.network)}if(status!=='all'){clauses.push('status=?');binds.push(status)}if(url.searchParams.get('origin')){const origin=url.searchParams.get('origin'),directory=sellerDirectory((await discovery(db)).resources),addresses=[...directory].filter(([,v])=>v.origin===origin&&!v.ambiguous).map(([k])=>k);if(!addresses.length)clauses.push('0');else{clauses.push("network||':'||CASE WHEN network IN ('Base','BSC') THEN lower(pay_to) ELSE pay_to END IN ("+addresses.map(()=>'?').join(',')+")");binds.push(...addresses)}}if(url.searchParams.get('facilitator')){clauses.push("(CASE WHEN source IN ('base-facilitator-indexer','solana-facilitator-indexer','xrpl-tag-indexer') THEN (SELECT context_key FROM chain_evidence ce WHERE ce.network=receipts.network AND ce.`transaction`=receipts.`transaction` AND ce.event_id=receipts.event_id) ELSE source END)=?");binds.push(url.searchParams.get('facilitator'))}if(p.q){clauses.push('(instr(lower(`transaction`),?)>0 OR instr(lower(COALESCE(payer,\'\')),?)>0 OR instr(lower(COALESCE(resource,\'\')),?)>0)');binds.push(p.q,p.q,p.q)}const where=clauses.join(' AND '),count=await db.prepare('SELECT COUNT(*) AS total FROM receipts WHERE '+where).bind(...binds).first(),items=(await db.prepare('SELECT *, (SELECT context_key FROM chain_evidence e WHERE e.network=receipts.network AND e.`transaction`=receipts.`transaction` AND e.event_id=receipts.event_id) AS facilitator_key FROM receipts WHERE '+where+' ORDER BY timestamp DESC LIMIT ? OFFSET ?').bind(...binds,p.limit,(p.page-1)*p.limit).all()).results;const catalog=sellerDirectory((await discovery(db)).resources);return json({items:items.map(r=>({...r,project:catalog.get(r.network+':'+(['Base','BSC'].includes(r.network)?String(r.pay_to||'').toLowerCase():r.pay_to))||null,facilitator:SOURCES.find(s=>s.role==='facilitator'&&s.id===(['base-facilitator-indexer','solana-facilitator-indexer','xrpl-tag-indexer'].includes(r.source)?r.facilitator_key:r.source))?.name||null,evidence:r.source==='bsc-indexer'?'finalized-router-event':r.source==='base-facilitator-indexer'?'facilitator-associated-authorization-transfer':r.source==='solana-facilitator-indexer'?'facilitator-signed-spl-transfer':r.source==='xrpl-tag-indexer'?'documented-source-tag-payment':'authenticated-source-report',explorer:NETWORKS.find(n=>n.id===r.network).explorer+r.transaction})),total:count.total,page:p.page,limit:p.limit,coverage:'Scoped BSC events, inferred Base facilitator authorization transfers and configured source receipts; not complete network history.'})}
if(path==='/api/projects'){const p=filterParams(url);const rows=(await db.prepare("SELECT * FROM projects WHERE status='approved' ORDER BY created_at DESC").all()).results.map(r=>publicProject(r)).filter(r=>(p.network==='All'||r.networks.includes(p.network))&&[r.name,r.description,r.category].join(' ').toLowerCase().includes(p.q));return json({items:rows.slice((p.page-1)*p.limit,p.page*p.limit),total:rows.length,page:p.page})}
if(path==='/api/submissions'){const u=requireUser(req);const rows=(await db.prepare('SELECT * FROM projects WHERE owner=? ORDER BY created_at DESC').bind(u.id).all()).results;return json({items:rows.map(r=>publicProject(r,true))})}
if(path==='/api/admin/submissions'){requireAdmin(req,env);const rows=(await db.prepare('SELECT * FROM projects ORDER BY created_at DESC LIMIT 200').all()).results;return json({items:rows.map(r=>publicProject(r,true))})}
if(path.startsWith('/api/projects/')){const id=decodeURIComponent(path.slice(14));const row=await db.prepare('SELECT * FROM projects WHERE id=?').bind(id).first();const own=row&&identity(req)?.id===row.owner;if(!row||row.status!=='approved'&&!own&&!isAdmin(req,env))throw new ApiError(404,'Project not found.');return json({project:publicProject(row,own||isAdmin(req,env)),reviews:(await db.prepare('SELECT action,note,created_at FROM reviews WHERE project_id=? ORDER BY created_at DESC').bind(id).all()).results})}
}
if(req.method==='POST'){
if(path==='/api/submissions'){csrf(req);const user=requireUser(req);await rate(db,'submit:'+user.id,5,86400000);const data=validateProject(await limitedJson(req));const duplicate=await db.prepare("SELECT id FROM projects WHERE owner=? AND website=? AND status IN ('pending','approved')").bind(user.id,data.website).first();if(duplicate)throw new ApiError(409,'This project already has an active submission.');const id=crypto.randomUUID(),now=Date.now();await db.prepare('INSERT INTO projects(id,owner,name,website,description,category,networks,endpoint,docs,contact,payment_terms,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'pending\',?,?)').bind(id,user.id,data.name,data.website,data.description,data.category,JSON.stringify(data.networks),data.endpoint,data.docs,data.contact,data.paymentTerms,now,now).run();return json({id,status:'pending',message:'Submitted for review. You can track it in My submissions.'},201)}
if(path==='/api/admin/indexers/run'){csrf(req);requireAdmin(req,env);await rate(db,'indexers-manual',1,60000);const data=await limitedJson(req);const run={Base:()=>syncBase(env,{force:true}),BSC:()=>syncBsc(env,BSC_TOPIC,{force:true}),Solana:()=>syncSolana(env),XRP:()=>syncXrp(env)};if(!Object.hasOwn(run,data.network))throw new ApiError(400,'Select Base, BSC, Solana or XRP.');return json(await run[data.network]())}
if(path==='/api/admin/bsc-sync'){csrf(req);requireAdmin(req,env);await rate(db,'bsc-manual-sync',1,60000);return json(await syncBsc(env,BSC_TOPIC,{force:true}))}
if(path==='/api/admin/sync'){csrf(req);requireAdmin(req,env);await rate(db,'admin-sync',1,60000);return json(await syncSources(env,{force:true}))}
if(path==='/api/admin/review'){csrf(req);requireAdmin(req,env);const data=await limitedJson(req);if(!['approved','rejected','pending'].includes(data.status)||!clean(data.id))throw new ApiError(400,'Invalid review.');const note=clean(data.note,2000);if(note.length<10)throw new ApiError(400,'Provide a review note of at least 10 characters.');const row=await db.prepare('SELECT id FROM projects WHERE id=?').bind(data.id).first();if(!row)throw new ApiError(404,'Project not found.');const now=Date.now();await db.batch([db.prepare('UPDATE projects SET status=?,review_note=?,updated_at=? WHERE id=?').bind(data.status,note,now,data.id),db.prepare('INSERT INTO reviews(id,project_id,actor,action,note,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),data.id,identity(req).id,data.status,note,now)]);return json({id:data.id,status:data.status})}
if(path.startsWith('/api/ingest/')){const source=path.slice(12);if(!SOURCES.some(s=>s.id===source))throw new ApiError(404,'Unknown source.');const reader=req.body?.getReader();if(!reader)throw new ApiError(400,'Body required.');let raw='',size=0;const decoder=new TextDecoder();for(;;){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_BODY){await reader.cancel();throw new ApiError(413,'Request too large.')}raw+=decoder.decode(value,{stream:true})}raw+=decoder.decode();await verifyWebhook(req,env,source,raw);let data;try{data=JSON.parse(raw)}catch{throw new ApiError(400,'Invalid JSON.')}if(!Array.isArray(data.receipts)||!data.receipts.length||data.receipts.length>100)throw new ApiError(400,'Supply 1 to 100 receipts.');await rate(db,'ingest:'+source,60,60000);const receipts=data.receipts.map(r=>validateReceipt(r,source));const statements=receipts.map(r=>db.prepare('INSERT INTO receipts(network,`transaction`,event_id,source,payer,pay_to,resource,asset,amount,decimals,timestamp,status,received_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(network,`transaction`,event_id) DO UPDATE SET status=excluded.status WHERE receipts.source=excluded.source AND receipts.status=\'pending\'').bind(r.network,r.transaction,r.eventId,r.source,r.payer,r.payTo,r.resource,r.asset,r.amount,r.decimals,r.timestamp,r.status,Date.now()));await db.batch(statements);return json({accepted:receipts.length,idempotent:true},202)}
}
throw new ApiError(404,'Endpoint not found.');}
export async function handleApi(req,env,ctx){try{return await api(req,env,ctx)}catch(e){if(!(e instanceof ApiError)&&!(e instanceof LookupError))console.error('API failure',e?.message);return json({error:e instanceof ApiError||e instanceof LookupError?e.message:'Service unavailable. Please try again later.'},e instanceof ApiError||e instanceof LookupError?e.status:503)}}
