// Read-only chain lookup. A chain transaction is not by itself proof of x402.
const RPC={Base:['BASE_RPC_URL','https://mainnet.base.org'],BSC:['BSC_RPC_URL','https://bsc-dataseed.bnbchain.org'],Solana:['SOLANA_RPC_URL','https://api.mainnet-beta.solana.com'],XRP:['XRPL_RPC_URL','https://xrplcluster.com']};
const EXPLORER={Base:'https://basescan.org/tx/',BSC:'https://bscscan.com/tx/',Solana:'https://solscan.io/tx/',XRP:'https://livenet.xrpl.org/transactions/'};
export class LookupError extends Error{constructor(status,message){super(message);this.status=status}}
export function validateLookup(network,hash){if(!RPC[network])throw new LookupError(400,'Select Base, Solana, XRP or BSC.');if(typeof hash!=='string'||!(network==='Solana'?/^[1-9A-HJ-NP-Za-km-z]{80,90}$/:network==='XRP'?/^[0-9a-fA-F]{64}$/:/^0x[0-9a-fA-F]{64}$/).test(hash))throw new LookupError(400,'Enter a valid transaction hash for the selected network.');return network==='Solana'?hash:hash.toLowerCase()}
async function rpc(env,network,method,params){let res;try{res=await fetch(env[RPC[network][0]]||RPC[network][1],{method:'POST',redirect:'manual',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(8000)})}catch{throw new LookupError(503,'The network provider did not respond. Retry or open this transaction in the blockchain explorer.')}if(!res.ok)throw new LookupError(503,'The network provider is unavailable (HTTP '+res.status+'). Use the blockchain explorer link below.');const reader=res.body.getReader();let bytes=0,parts=[];for(;;){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>2_000_000){await reader.cancel();throw new LookupError(503,'The transaction is too large for the inline viewer. Use the blockchain explorer.')}parts.push(value)}const buf=new Uint8Array(bytes);let i=0;for(const p of parts){buf.set(p,i);i+=p.length}let data;try{data=JSON.parse(new TextDecoder().decode(buf))}catch{throw new LookupError(503,'The network provider returned an unreadable response.')}if(data.error)throw new LookupError(503,'The network provider could not complete this lookup.');return data.result;}
const qty=v=>{if(typeof v!=='string'||!/^0x[\da-f]+$/i.test(v))throw new LookupError(503,'The network provider returned invalid transaction data.');return BigInt(v)};
export async function lookupTransaction(env,network,input){const hash=validateLookup(network,input),base={network,hash,explorer:EXPLORER[network]+hash,checkedAt:Date.now(),evidence:'blockchain-transaction',x402Verified:false};
 if(network==='Base'||network==='BSC'){const [chain,tx,receipt]=await Promise.all([rpc(env,network,'eth_chainId',[]),rpc(env,network,'eth_getTransactionByHash',[hash]),rpc(env,network,'eth_getTransactionReceipt',[hash])]);if(qty(chain)!==BigInt(network==='Base'?8453:56))throw new LookupError(503,'The configured provider is connected to the wrong network.');if(!tx)throw new LookupError(404,'Transaction not found on this network. Check the selected chain or try again after it is confirmed.');if(tx.hash?.toLowerCase()!==hash||receipt&&receipt.transactionHash?.toLowerCase()!==hash)throw new LookupError(503,'Transaction identity did not match the requested hash.');const block=receipt?await rpc(env,network,'eth_getBlockByNumber',[receipt.blockNumber,false]):null;if(receipt&&(!block||block.hash?.toLowerCase()!==receipt.blockHash?.toLowerCase()))throw new LookupError(503,'Transaction block could not be confirmed.');return{...base,status:!receipt?'pending':qty(receipt.status)===1n?'confirmed':'failed',from:tx.from,to:tx.to||null,block:receipt?Number(qty(receipt.blockNumber)):null,timestamp:block?Number(qty(block.timestamp))*1000:null,nativeAmount:qty(tx.value).toString(),nativeSymbol:network==='Base'?'ETH':'BNB',nativeDecimals:18,tokenTransfers:(receipt?.logs||[]).filter(l=>!l.removed&&l.topics?.length===3&&l.topics[0]?.toLowerCase()==='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'&&l.topics.slice(1).every(t=>/^0x[0-9a-f]{64}$/i.test(t))&&/^0x[0-9a-f]{64}$/i.test(l.data)).map(l=>({asset:l.address,from:'0x'+l.topics[1].slice(-40),to:'0x'+l.topics[2].slice(-40),rawAmount:BigInt(l.data).toString()})),fee:receipt?{amount:(qty(receipt.gasUsed)*qty(receipt.effectiveGasPrice||tx.gasPrice)).toString(),symbol:network==='Base'?'ETH':'BNB',decimals:18}:null};}
 if(network==='Solana'){const tx=await rpc(env,network,'getTransaction',[hash,{encoding:'jsonParsed',commitment:'finalized',maxSupportedTransactionVersion:0}]);if(!tx)throw new LookupError(404,'Finalized transaction not found. The public provider may not retain its history.');if(tx.transaction?.signatures?.[0]!==hash)throw new LookupError(503,'Transaction signature did not match.');const keys=tx.transaction.message?.accountKeys||[];return{...base,status:tx.meta?tx.meta.err?'failed':'finalized':'unknown',from:keys.find(k=>k.signer)?.pubkey||null,to:null,block:tx.slot,timestamp:tx.blockTime?tx.blockTime*1000:null,fee:tx.meta?{amount:String(tx.meta.fee),symbol:'SOL',decimals:9}:null,tokenChanges:(tx.meta?.postTokenBalances||[]).map(p=>{const pre=tx.meta.preTokenBalances?.find(b=>b.accountIndex===p.accountIndex&&b.mint===p.mint);return{owner:p.owner||null,asset:p.mint,change:(BigInt(p.uiTokenAmount.amount)-BigInt(pre?.uiTokenAmount?.amount||'0')).toString(),decimals:p.uiTokenAmount.decimals}})};}
 const result=await rpc(env,network,'tx',[{transaction:hash,binary:false,api_version:2}]);if(result?.error==='txnNotFound')throw new LookupError(404,'Transaction not found in the provider’s retained XRP Ledger history.');if(!result||result.error)throw new LookupError(503,'XRP Ledger could not complete this lookup.');const tx=result.tx_json||result;if((result.hash||tx.hash)?.toLowerCase()!==hash)throw new LookupError(503,'Transaction hash did not match.');const outcome=result.meta?.TransactionResult;return{...base,status:!result.validated?'pending':outcome==='tesSUCCESS'?'validated':outcome?'failed':'unknown',type:tx.TransactionType,from:tx.Account,to:tx.Destination||null,block:result.ledger_index,timestamp:tx.date!=null?(tx.date+946684800)*1000:null,fee:tx.Fee?{amount:tx.Fee,symbol:'XRP',decimals:6}:null,delivered:result.meta?.delivered_amount||null};
}
