const json=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
export async function newsApi(req,env){const u=new URL(req.url);if(!['/api/live/news','/api/live/editor'].includes(u.pathname))return null;
if(u.pathname.endsWith('/editor')){if(!env.LOCAL_EDITOR||!['127.0.0.1:4174','localhost:4174'].includes(u.host))return json({error:'Local editor only'},403);
if(req.method==='GET')return json({items:(await env.DB.prepare('SELECT * FROM editorial_articles ORDER BY updated_at DESC').all()).results});
if(req.method!=='POST'||req.headers.get('origin')!==u.origin)return json({error:'Same-origin editor required'},403);
const text=await req.text();if(text.length>100000)return json({error:'Article too large'},413);let d;try{d=JSON.parse(text)}catch{return json({error:'Invalid JSON'},400)};
if(typeof d.title!=='string'||d.title.length<3||d.title.length>160||typeof d.body!=='string'||d.body.length<20||d.body.length>80000||typeof d.summary!=='string'||d.summary.length>500||!['draft','published'].includes(d.status)||d.id&&!/^[a-f0-9-]{36}$/.test(d.id))return json({error:'Add a title, summary and article text (20+ characters).'},400);
const id=d.id||crypto.randomUUID(),now=Date.now();await env.DB.prepare('INSERT INTO editorial_articles VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,summary=excluded.summary,body=excluded.body,status=excluded.status,updated_at=excluded.updated_at').bind(id,d.title,d.summary,d.body,d.status,now,now).run();return json({id,status:d.status});}
if(req.method!=='GET')return json({error:'Read only'},405);const articles=(await env.DB.prepare("SELECT * FROM editorial_articles WHERE status='published' ORDER BY created_at DESC").all()).results;const snaps=(await env.DB.prepare("SELECT source,payload,checked_at FROM external_snapshots WHERE source LIKE 'news-%'").all()).results;return json({articles,items:snaps.flatMap(s=>JSON.parse(s.payload).items||[]).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)),sources:snaps.map(s=>({source:s.source,checkedAt:s.checked_at})),localEditor:!!env.LOCAL_EDITOR,xConfigured:!!(env.X_BEARER_TOKEN&&env.X_NEWS_ENABLED==='true')});}
export async function syncNews(env){const feeds=[{id:'news-dev',url:'https://dev.to/api/articles?tag=x402&per_page=30',map:p=>({id:'dev-'+p.id,title:p.title,url:p.url,date:p.published_at,author:p.user?.name,source:'DEV Community',kind:'Community article'})},{id:'news-releases',url:'https://api.github.com/repos/coinbase/x402/releases?per_page=20',map:p=>({id:'release-'+p.id,title:p.name||p.tag_name,url:p.html_url,date:p.published_at,author:p.author?.login,source:'coinbase/x402',kind:'Protocol release'})}];
if(env.X_NEWS_ENABLED==='true'&&env.X_BEARER_TOKEN)feeds.push({id:'news-x',url:'https://api.x.com/2/tweets/search/recent?query='+encodeURIComponent('x402 -is:retweet')+'&max_results=10&tweet.fields=created_at,author_id',headers:{Authorization:'Bearer '+env.X_BEARER_TOKEN},map:p=>({id:'x-'+p.id,title:p.text.slice(0,220),url:'https://x.com/i/web/status/'+p.id,date:p.created_at,author:p.author_id,source:'X',kind:'Social post'})});
if(env.TWITTERAPI_IO_ENABLED==='true'&&env.TWITTERAPI_IO_KEY)feeds.push({id:'news-twitterapi',url:'https://api.twitterapi.io/twitter/tweet/advanced_search?query='+encodeURIComponent('x402 -filter:retweets')+'&queryType=Latest',headers:{'X-API-Key':env.TWITTERAPI_IO_KEY},map:p=>({id:'x-'+p.id,title:p.text.slice(0,220),url:'https://x.com/i/web/status/'+p.id,date:p.createdAt,author:p.author?.userName,source:'X via TwitterAPI.io',kind:'Social post'})});
let indexed=0;for(const f of feeds){const old=await env.DB.prepare('SELECT checked_at FROM external_snapshots WHERE source=?').bind(f.id).first();if(old&&Date.now()-old.checked_at<3600000)continue;try{const attempt=await env.DB.prepare('SELECT checked_at FROM external_snapshots WHERE source=?').bind('attempt-'+f.id).first();if(attempt&&Date.now()-attempt.checked_at<3600000)continue;await env.DB.prepare('INSERT INTO external_snapshots VALUES(?,?,?) ON CONFLICT(source) DO UPDATE SET checked_at=excluded.checked_at').bind('attempt-'+f.id,'{}',Date.now()).run();const r=await fetch(f.url,{headers:{'User-Agent':'X402blockchains-news','Accept':'application/json',...f.headers},redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status);const raw=await r.json(),rows=f.id==='news-x'?raw.data||[]:f.id==='news-twitterapi'?raw.tweets||[]:raw;if(!Array.isArray(rows))throw Error('Invalid feed');const items=rows.map(f.map).filter(p=>typeof p.title==='string'&&/^https:\/\//.test(p.url)&&Number.isFinite(Date.parse(p.date)));await env.DB.prepare('INSERT INTO external_snapshots VALUES(?,?,?) ON CONFLICT(source) DO UPDATE SET payload=excluded.payload,checked_at=excluded.checked_at').bind(f.id,JSON.stringify({items}),Date.now()).run();indexed+=items.length;}catch(e){console.warn('News source '+f.id+': '+e.message)}}return{indexed};}
