import {discovery,groupOrigins,ApiError,limitedJson} from './backend.mjs';
import {sellerDirectory} from './analytics.mjs';
import {NETWORKS,safeUrl} from './sources.mjs';
const logoList=(env,p)=>{if(p.logo&&safeUrl(p.logo))return [p.logo];const declared=p.services?.map(r=>safeUrl(r.iconUrl)).filter(Boolean);if(declared?.length)return [...new Set(declared)];const urls=[p.website,p.url,p.docs];for(const u of urls){try{const found=env.LOGOS?.[new URL(u).origin];const branded=found?.filter(x=>!x.includes('assets.vercel.com/')&&!x.includes('github.githubassets.com/favicons/'));if(branded?.length)return branded}catch{}}return []};
const CHAINS=['Base','BSC','Solana'];
const facSource="CASE WHEN r.source IN ('base-facilitator-indexer','bsc-facilitator-indexer','bsc-explorer-payment','bsc-authorization-indexer','bsc-documented-settlement','solana-facilitator-indexer') THEN e.context_key WHEN r.source='bsc-indexer' THEN 'wtf' ELSE r.source END";
const addr=(n,a)=>['Base','BSC'].includes(n)?String(a||'').toLowerCase():String(a||'');
const sha=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
const safePublic=s=>{const {contact,email,...p}=s;return p};
function filters(url){const asOf=Number(url.searchParams.get('asOf')||Date.now());if(!Number.isSafeInteger(asOf)||asOf<1500000000000||asOf>Date.now()+60000)throw new ApiError(400,'Invalid comparison timestamp');const network=url.searchParams.get('network')||'All',days=Number(url.searchParams.get('days')??30),page=Number(url.searchParams.get('page')||1),limit=Number(url.searchParams.get('limit')||20),q=(url.searchParams.get('q')||'').trim().toLowerCase();if(network!=='All'&&!CHAINS.includes(network)||![0,1,7,15,30].includes(days)||!Number.isInteger(page)||page<1||page>100000||!Number.isInteger(limit)||limit<1||limit>100||q.length>150)throw new ApiError(400,'Invalid filters');return{network,days,page,limit,q,asOf}}
export function tokenInfo(network,asset){let key=asset?.toLowerCase();const known={Base:{'0x833589fcd6edb6e08f4c7c32d4f71b54bda02913':'USDC'},BSC:{'0x55d398326f99059ff775485246999027b3197955':'USDT','0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d':'USDC'},Solana:{'epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v':'USDC'}};return known[network]?.[key]||'Token'}
export function formatUnits(value,decimals){if(!/^\d+$/.test(String(value))||!Number.isInteger(decimals)||decimals<0||decimals>36)return null;let s=String(value).padStart(decimals+1,'0');return decimals?s.slice(0,-decimals)+(s.slice(-decimals).replace(/0+$/,'')?'.'+s.slice(-decimals).replace(/0+$/,''):''):s}
export function stablecoinEquivalent(volumes){let total=0n,included=0,excluded=0;for(const v of volumes){const decimals=v.decimals;if(!['USDC','USDT'].includes(tokenInfo(v.network,v.asset))||!Number.isInteger(decimals)||decimals<0||decimals>18||!/^\d+$/.test(String(v.atomic))){excluded++;continue}total+=BigInt(v.atomic)*10n**BigInt(18-decimals);included++}return {amount:included?formatUnits(total.toString(),18):null,includedAssets:included,excludedAssets:excluded,basis:'USDC and USDT at $1 face value; not market-priced USD',complete:false}}
export async function portal(req,env){const url=new URL(req.url);if(!url.pathname.startsWith('/api/live/'))return null;try{if(url.pathname==='/api/live/applications')return await applications(req,env,url);if(req.method!=='GET')throw new ApiError(405,'Method not allowed');const f=filters(url),db=env.DB,dir=await discovery(db),sellerMap=sellerDirectory(dir.resources),allProjects=groupOrigins(dir.resources).filter(p=>p.networks.some(n=>CHAINS.includes(n))),facilitators=dir.sources.filter(s=>s.role==='facilitator'&&[...s.declared,...s.networks].some(n=>CHAINS.includes(n)));
const externals=(await db.prepare('SELECT payload FROM external_sellers').all()).results.map(r=>JSON.parse(r.payload));for(const p of externals){if(!allProjects.some(x=>x.website===p.website))allProjects.push({...p,id:encodeURIComponent(p.website),services:[],sources:[p.source],evidence:'external-directory'})}
// External directory wallets participate in attribution, but shared wallets stay ambiguous.
for(const p of externals)for(const w of p.wallets||[]){const key=w.network+':'+addr(w.network,w.address),prior=sellerMap.get(key);if(!prior)sellerMap.set(key,{name:p.name,origin:p.website,description:p.description,ambiguous:false});else if(prior.origin!==p.website)prior.ambiguous=true;}
const approved=(await db.prepare("SELECT id,payload FROM portal_applications WHERE status='approved'").all()).results.map(r=>({...safePublic(JSON.parse(r.payload)),id:r.id,evidence:'operator-reviewed-listing',resources:0}));for(const p of approved){if(p.role!=='Facilitator'&&!allProjects.some(x=>x.website===p.website))allProjects.push({...p,services:[],sources:['local-review']});if(['Facilitator','Project and facilitator'].includes(p.role))facilitators.push({...p,url:p.website,docs:p.docs,declared:p.networks,networks:p.networks,state:'operator-reviewed',note:'Operator-reviewed listing. No automatic settlement verification.'})}
const hiddenForLogo=allProjects.filter(p=>!logoList(env,p).length).length;for(let i=allProjects.length-1;i>=0;i--)if(!logoList(env,allProjects[i]).length)allProjects.splice(i,1);
const since=f.days?f.asOf-f.days*86400000:0,binds=[since,f.asOf];let where="r.status='settled' AND r.network IN ('Base','BSC','Solana') AND r.timestamp>=? AND r.timestamp<=?";if(f.network!=='All'){where+=' AND r.network=?';binds.push(f.network)}const facilitator=url.searchParams.get('facilitator'),origin=url.searchParams.get('origin'),wallet=url.searchParams.get('wallet');if(facilitator){where+=' AND '+facSource+'=?';binds.push(facilitator)}if(origin){const keys=[...sellerMap].filter(([,v])=>v.origin===origin&&!v.ambiguous).map(([k])=>k);where+=keys.length?" AND r.network||':'||CASE WHEN r.network IN ('Base','BSC') THEN lower(r.pay_to) ELSE r.pay_to END IN ("+keys.map(()=>'?').join(',')+")":' AND 0';binds.push(...keys)}if(wallet){if(f.network==='All'||!(/^[a-zA-Z0-9]{20,100}$/.test(wallet)))throw new ApiError(400,'Choose a chain and valid wallet address');where+=" AND (CASE WHEN r.network IN ('Base','BSC') THEN lower(r.payer) ELSE r.payer END=? OR CASE WHEN r.network IN ('Base','BSC') THEN lower(r.pay_to) ELSE r.pay_to END=?)";binds.push(addr(f.network,wallet),addr(f.network,wallet))}
const from=' FROM receipts r LEFT JOIN chain_evidence e ON e.network=r.network AND e.`transaction`=r.`transaction` AND e.event_id=r.event_id WHERE '+where;
const projectPublic=p=>({id:p.id,name:p.name,website:p.website,description:p.description,networks:p.networks.filter(n=>CHAINS.includes(n)),sources:p.sources,resources:p.services.length,reportedResources:p.reportedResources||null,reference:p.reference||null,evidence:p.evidence||'provider-catalog',logos:logoList(env,p),logo:logoList(env,p)[0]||null});
const page=url.pathname.slice(10);
if(page==='transactions'){let clause='',searchBind=[];if(f.q){clause=" AND (instr(lower(r.`transaction`),?)>0 OR instr(lower(COALESCE(r.payer,'')),?)>0 OR instr(lower(COALESCE(r.pay_to,'')),?)>0 OR instr(lower(COALESCE(r.resource,'')),?)>0)";searchBind=Array(4).fill(f.q);const sellers=[...sellerMap].filter(([,p])=>[p.name,p.origin].join(' ').toLowerCase().replace(/[\s-]/g,'').includes(f.q.replace(/[\s-]/g,''))).map(([k])=>k);const facIds=facilitators.filter(p=>[p.name,p.id].join(' ').toLowerCase().replace(/[\s-]/g,'').includes(f.q.replace(/[\s-]/g,''))).map(p=>p.id);if(sellers.length||facIds.length){clause=clause.slice(0,-1);if(sellers.length){clause+=" OR r.network||':'||CASE WHEN r.network IN ('Base','BSC') THEN lower(r.pay_to) ELSE r.pay_to END IN ("+sellers.map(()=>'?').join(',')+")";searchBind.push(...sellers)}if(facIds.length){clause+=' OR '+facSource+' IN ('+facIds.map(()=>'?').join(',')+')';searchBind.push(...facIds)}clause+=')'}}const count=await db.prepare('SELECT COUNT(*) total'+from+clause).bind(...binds,...searchBind).first();const rows=(await db.prepare('SELECT r.*,e.block_number,e.block_hash,e.contract,'+facSource+' facilitator_id'+from+clause+(url.searchParams.get('order')==='mixed'&&f.network==='All'?' ORDER BY ROW_NUMBER() OVER (PARTITION BY r.network ORDER BY CASE WHEN e.context_key=\'xpay\' THEN 0 ELSE 1 END,r.timestamp DESC,r.`transaction`,r.event_id),CASE r.network WHEN \'Base\' THEN 0 WHEN \'Solana\' THEN 1 ELSE 2 END':' ORDER BY r.timestamp DESC,r.`transaction`,r.event_id')+' LIMIT ? OFFSET ?').bind(...binds,...searchBind,f.limit,(f.page-1)*f.limit).all()).results;return json({items:rows.map(r=>{const p=sellerMap.get(r.network+':'+addr(r.network,r.pay_to));return{...r,amountFormatted:formatUnits(r.amount,r.decimals),symbol:tokenInfo(r.network,r.asset),project:p&&!p.ambiguous?p:null,facilitator:facilitators.find(s=>s.id===r.facilitator_id)?.name||null,explorer:NETWORKS.find(n=>n.id===r.network)?.explorer+r.transaction,evidence:r.source==='bsc-explorer-payment'?'AEON-reported payment; USDT settlement checked on-chain; x402 classification supplied by provider':r.source==='bsc-documented-settlement'?'Documented historical settlement':['bsc-indexer','bsc-authorization-indexer'].includes(r.source)?'Router settlement / authorization event':'Facilitator-associated transfer; HTTP resource not proven'}}),total:count.total,...f,coverage:'Indexed payment events only; not complete chain history.'})}
if(page==='projects'){let rows=allProjects.map(projectPublic).filter(p=>(f.network==='All'||p.networks.includes(f.network))&&[p.name,p.website,p.description].join(' ').toLowerCase().replace(/[\s-]/g,'').includes(f.q.replace(/[\s-]/g,'')));return json({items:rows.slice((f.page-1)*f.limit,f.page*f.limit),total:rows.length,hiddenForLogo,...f})}
if(page==='project'){const p=allProjects.find(p=>p.website===origin);if(!p)throw new ApiError(404,'Project not found');return json({...projectPublic(p),items:p.services.slice((f.page-1)*f.limit,f.page*f.limit),total:p.services.length,page:f.page,limit:f.limit,wallets:[...new Map(p.services.flatMap(r=>r.accepts.map(a=>[a.network+':'+a.payTo,{network:a.network,address:a.payTo}]))).values()]})}
if(page==='facilitators'){const rows=facilitators.filter(p=>logoList(env,p).length).filter(p=>(f.network==='All'||[...p.networks,...p.declared].includes(f.network))&&[p.name,p.url].join(' ').toLowerCase().replace(/[\s-]/g,'').includes(f.q.replace(/[\s-]/g,''))).sort((a,b)=>(b.id==='xpay')-(a.id==='xpay')||a.name.localeCompare(b.name));const counts=(await db.prepare('SELECT '+facSource+' id,COUNT(DISTINCT r.network||r.`transaction`) transactions'+from+' GROUP BY 1').bind(...binds).all()).results;return json({items:rows.slice((f.page-1)*f.limit,f.page*f.limit).map(p=>({...p,transactions:counts.find(r=>r.id===p.id)?.transactions||0,networks:[...new Set([...p.networks,...p.declared])].filter(n=>CHAINS.includes(n)),logos:logoList(env,p),logo:logoList(env,p)[0]||null,verified:false})),total:rows.length,hiddenForLogo,...f})}
if(page==='summary'){const totals=await db.prepare("SELECT COUNT(DISTINCT r.network||':'||r.`transaction`) transactions,COUNT(*) events,COUNT(DISTINCT CASE WHEN r.payer<>'' THEN r.network||':'||CASE WHEN r.network IN ('Base','BSC') THEN lower(r.payer) ELSE r.payer END END) buyers,COUNT(DISTINCT CASE WHEN r.pay_to<>'' THEN r.network||':'||CASE WHEN r.network IN ('Base','BSC') THEN lower(r.pay_to) ELSE r.pay_to END END) sellers,MAX(r.timestamp) latest"+from).bind(...binds).first();const history=(await db.prepare("SELECT CAST(r.timestamp/86400000 AS INTEGER)*86400000 time,r.network,COUNT(DISTINCT r.`transaction`) transactions"+from+' GROUP BY 1,2 ORDER BY 1').bind(...binds).all()).results;const networks=(await db.prepare('SELECT r.network,COUNT(DISTINCT r.`transaction`) transactions,COUNT(DISTINCT r.payer) buyers,COUNT(DISTINCT r.pay_to) sellers'+from+' GROUP BY 1').bind(...binds).all()).results;const volumes=(await db.prepare('SELECT r.network,r.asset,r.decimals,sum_atomic(r.amount) atomic'+from+' GROUP BY r.network,r.asset,r.decimals').bind(...binds).all()).results;return json({...totals,volumeUsd:null,stablecoinVolume:stablecoinEquivalent(volumes),projects:allProjects.filter(p=>f.network==='All'||p.networks.includes(f.network)).length,resources:dir.resources.filter(r=>r.accepts.some(a=>CHAINS.includes(a.network)&&(f.network==='All'||a.network===f.network))).length,facilitators:facilitators.filter(p=>logoList(env,p).length).filter(p=>f.network==='All'||[...p.networks,...p.declared].includes(f.network)).length,history,networks:CHAINS.map(n=>({network:n,transactions:0,buyers:0,sellers:0,...networks.find(r=>r.network===n),projects:allProjects.filter(p=>p.networks.includes(n)).length})),tokenVolumes:volumes.map(v=>({...v,amount:formatUnits(v.atomic,v.decimals),symbol:tokenInfo(v.network,v.asset)})),updatedAt:Date.now(),window:{from:since,to:f.asOf,timezone:'UTC'},coverage:'Partial indexed coverage. Counts are not a complete ecosystem total. Token volumes are not USD valuations.',...f})}
if(page==='external'){const rows=(await db.prepare('SELECT * FROM external_snapshots').all()).results;return json({sources:rows.map(r=>({source:r.source,checkedAt:r.checked_at,data:JSON.parse(r.payload)})),scope:'External reported statistics; not merged into indexed transaction totals.'})}
if(page==='coverage'){return json({chains:CHAINS,complete:false,snapshotAt:dir.snapshotAt,hiddenForLogo,catalogFeeds:(await db.prepare("SELECT id,checked_at,success_at,error,payload FROM source_cache WHERE id IN ('xpay-direct','agora-directory')").all()).results.map(r=>({...r,payload:JSON.parse(r.payload)})),sources:dir.sources.map(s=>({id:s.id,name:s.name,url:s.url,reference:s.reference,state:s.state,networks:s.networks,declared:s.declared,checkedAt:s.checkedAt,error:s.error,catalog:s.catalog})),cursors:(await db.prepare('SELECT * FROM chain_cursors').all()).results,addressHistory:await db.prepare("SELECT COUNT(*) addresses,SUM(complete) completed,MIN(checked_at) oldestCheck FROM address_backfills").first().catch(()=>null),priorityHistory:(await db.prepare("SELECT id,complete,checked_at,error,verified FROM address_backfills WHERE id='xpay-merchant'").all().catch(()=>({results:[]}))).results,native:(await db.prepare('SELECT * FROM indexer_state').all()).results,runs:(await db.prepare('SELECT * FROM collector_runs').all()).results,notes:['Catalog listings do not establish payment volume.','A project receiving payments and a facilitator settling payments are separate roles.','No guarantee of parity with x402scan; definitions, source coverage and time windows may differ.']})}
throw new ApiError(404,'API route not found');}catch(e){return json({error:e instanceof ApiError?e.message:'Local backend request failed'},e.status||500)}}
async function applications(req,env,url){const db=env.DB;if(req.method==='GET'){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token)throw new ApiError(401,'Submission receipt required');const row=await db.prepare('SELECT id,status,note,created_at,updated_at FROM portal_applications WHERE id=? AND token_hash=?').bind(url.searchParams.get('id'),await sha(token)).first();if(!row)throw new ApiError(404,'Submission not found');return json(row)}if(req.method!=='POST')throw new ApiError(405,'Method not allowed');if(req.headers.get('origin')!==url.origin)throw new ApiError(403,'Same-origin submission required');const d=await limitedJson(req,16000);const text=(v,n)=>typeof v==='string'?v.trim().slice(0,n):'';const p={name:text(d.name,100),website:safeUrl(d.website),description:text(d.description,2000),endpoint:safeUrl(d.endpoint),docs:safeUrl(d.docs),contact:text(d.email,200),role:text(d.role,60),networks:Array.isArray(d.chains)?[...new Set(d.chains.map(c=>c==='BNB Chain'?'BSC':c))]:[],logo:d.logo?safeUrl(d.logo):null};if(p.name.length<2||p.description.length<20||!p.website||!p.endpoint||!p.docs||!/^\S+@\S+\.\S+$/.test(p.contact)||!['Facilitator','Project / API','AI agent','Project and facilitator'].includes(p.role)||!p.networks.length||p.networks.some(n=>!CHAINS.includes(n))||!p.logo)throw new ApiError(400,'Complete the required listing information with HTTPS links.');const recent=await db.prepare('SELECT count(*) n FROM portal_applications WHERE created_at>?').bind(Date.now()-3600000).first();if(recent.n>=20)throw new ApiError(429,'Submission limit reached; please try later.');const id=crypto.randomUUID(),token=crypto.randomUUID()+crypto.randomUUID(),now=Date.now();await db.prepare('INSERT INTO portal_applications(id,payload,token_hash,created_at,updated_at) VALUES(?,?,?,?,?)').bind(id,JSON.stringify(p),await sha(token),now,now).run();return json({id,token,status:'pending',message:'Saved in the local database for review. No ownership verification or publication has occurred.'},201)}
