// Fetch public metadata only. Never verifies, settles, or sends a payment.
import fs from 'node:fs/promises';
import {SOURCES,normalizeResources,networkName} from '../server/sources.mjs';
const previous=(await import('../server/catalog-snapshot.mjs')).SNAPSHOT;
const resources=[],sources=[];
async function get(url){const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const text=await r.text();if(text.length>8_000_000)throw new Error('Response exceeds catalog safety limit');return JSON.parse(text)}
async function read(s){const checkedAt=Date.now(),entry={id:s.id,checkedAt,successAt:null,networks:[],kinds:[],error:null,catalog:null};let found=[];
 try{const d=await get(s.url+s.supported);if(!Array.isArray(d.kinds))throw new Error('Unsupported network response');entry.kinds=d.kinds.map(k=>({network:networkName(k.network),networkId:k.network,scheme:k.scheme,version:k.x402Version})).filter(k=>k.network);entry.networks=[...new Set(entry.kinds.map(k=>k.network))];entry.successAt=checkedAt;}catch(e){entry.error=e.message}
 if(s.discovery){let offset=0,total=null,complete=false,last='';try{for(let page=0;page<1000;page++){const d=await get(s.url+s.discovery+'?limit=100&offset='+offset);if(!Array.isArray(d.items))throw new Error('Unsupported catalog response');const fingerprint=JSON.stringify(d.items.map(r=>[r.resource||r.url,r.method]));if(d.items.length&&fingerprint===last)throw new Error('Provider repeated a page');last=fingerprint;found.push(...normalizeResources(d,s.id));total=Number.isSafeInteger(d.pagination?.total)?d.pagination.total:null;offset+=d.items.length;complete=total!==null?offset>=total:d.items.length<100;if(complete)break;if(!d.items.length)throw new Error('Provider ended before reported total');if(page%10===0)console.log(s.id+': '+offset+' source records scanned');}if(!complete)throw new Error('Catalog requires more than 1000 pages');entry.catalog={offset,total,complete,fetched:found.length,error:null,updatedAt:Date.now()};}catch(e){entry.catalog={offset,total,complete:false,fetched:found.length,error:e.message,updatedAt:Date.now()};const old=previous.resources.filter(r=>r.source===s.id);const keys=new Set(found.map(r=>r.method+' '+r.url));found.push(...old.filter(r=>!keys.has(r.method+' '+r.url)));}}
 resources.push(...found);sources.push(entry);console.log(JSON.stringify({source:s.id,connected:!entry.error,records:found.length,catalog:entry.catalog,error:entry.error}));}
const queue=SOURCES.filter(s=>s.supported);await Promise.all(Array.from({length:4},async()=>{while(queue.length)await read(queue.shift())}));
const snapshot={generatedAt:Date.now(),sources,resources};await fs.writeFile('server/catalog-snapshot.mjs','// Public provider catalog snapshot; timestamps and provenance retained.\nexport const SNAPSHOT='+JSON.stringify(snapshot)+';\n');console.log(JSON.stringify({services:resources.length,providers:sources.length,bytes:JSON.stringify(snapshot).length}));
